put test driver in container, removed package readmes

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -42,22 +42,29 @@ jobs:
         run: |
           docker run -d --name proxy -p 8000:8000 proxy_image:latest
 
-      - name: Set up Python
-        uses: actions/setup-python@v2
-        with:
-          python-version: '3.9'
-
-      - name: Install pip dependencies
+      - name: Build and Run Test Driver
         run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
+          docker build -t test_driver_image -f driver.Dockerfile .
+          docker run --name test_driver_container test_driver_image
 
-      - name: Run end-to-end tests
+      - name: Get Test Driver Exit Code
+        id: get_test_driver_exit_code
         run: |
-          python test/e2e/e2e_test.py
+          docker inspect test_driver_container --format='{{.State.ExitCode}}' > exit_code.txt
+          cat exit_code.txt
+        continue-on-error: true
 
       - name: Archive test reports
         uses: actions/upload-artifact@v2
         with:
           name: test-reports
           path: reports/
+
+      - name: Fail the job if tests failed
+        if: failure()
+        run: |
+          exit_code=$(cat exit_code.txt)
+          if [ "$exit_code" -ne 0 ]; then
+            echo "Tests failed with exit code $exit_code"
+            exit $exit_code
+          fi
